<?php

/**
 * Paystack Magento2 Module using \Magento\Payment\Model\Method\AbstractMethod
 * Copyright (C) 2019 Paystack.com
 *
 * This file is part of Pstk/Paystack.
 *
 * Pstk/Paystack is free software => you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http =>//www.gnu.org/licenses/>.
 */

namespace Pstk\Paystack\Controller\Payment;

class Webhook extends AbstractPaystackStandard
{

    public function execute() {
        $finalMessage = "failed";

        $resultFactory = $this->resultFactory->create(\Magento\Framework\Controller\ResultFactory::TYPE_RAW);
        try {

            // Retrieve the request's body and parse it as JSON
            $rawBody = $this->request->getContent();
            http_response_code(200);

            $this->logger->info("Paystack Webhook: received request");

            // Validate webhook signature
            $signature = $this->request->getHeader('X-Paystack-Signature') ?: '';
            if (!$signature || !$this->paystackClient->validateWebhookSignature($rawBody, $signature)) {
                $this->logger->warning("Paystack Webhook: signature validation failed");
                $resultFactory->setContents("auth failed");
                return $resultFactory;
            }

            $this->logger->info("Paystack Webhook: signature valid");

            $event = json_decode($rawBody);
            if (!$event) {
                $resultFactory->setContents("invalid payload");
                return $resultFactory;
            }

            $this->logger->info("Paystack Webhook: event type = " . ($event->event ?? 'unknown'));

            switch ($event->event) {
                case 'charge.success':
                    if ('success' === $event->data->status) {
                        $transactionDetails = $this->paystackClient->verifyTransaction($event->data->reference);

                        $reference = $transactionDetails->data->reference;
                        $this->logger->info("Paystack Webhook: verified transaction", ['reference' => $reference]);

                        $this->paystackClient->logTransactionSuccess($reference, $this->configProvider->getPublicKey());

                        $order = $this->orderInterface->loadByIncrementId($reference);

                        // In popup mode, reference is generated by Paystack and we provided quoteId instead
                        if ((!$order || !$order->getId()) && isset($event->data->metadata->quoteId)) {
                            $this->logger->info("Paystack Webhook: order not found by reference, searching by quoteId", ['quoteId' => $event->data->metadata->quoteId]);
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $searchCriteriaBuilder = $objectManager->create('Magento\Framework\Api\SearchCriteriaBuilder');
                            $searchCriteria = $searchCriteriaBuilder->addFilter('quote_id', $event->data->metadata->quoteId, 'eq')->create();
                            $items = $this->orderRepository->getList($searchCriteria);
                            if ($items->getTotalCount() == 1) {
                                $order = $items->getFirstItem();
                            }
                        }

                        if ($order && $order->getId()) {
                            $this->logger->info("Paystack Webhook: order found, dispatching verify event", [
                                'order_id' => $order->getIncrementId(),
                                'current_status' => $order->getStatus(),
                            ]);
                            // dispatch the `payment_verify_after` event to update the order status
                            $this->eventManager->dispatch('paystack_payment_verify_after', [
                                "paystack_order" => $order,
                            ]);

                            $resultFactory->setContents("success");
                            return $resultFactory;
                        }
                        $this->logger->warning("Paystack Webhook: order not found for reference " . $reference);
                    }
                    break;
            }
        } catch (\Exception $exc) {
            $this->logger->error("Paystack Webhook: exception", ['error' => $exc->getMessage()]);
            $finalMessage = $exc->getMessage();
        }

        $resultFactory->setContents($finalMessage);
        return $resultFactory;
    }
}
