#!/usr/bin/env bash

set -eux 

chown -R www-data:www-data /var/www/html/var/composer_home

# Install Magento, enable lomi. module, compile
su www-data <<EOSU
/var/www/html/bin/magento setup:install --base-url=$MAGENTO_URL --backend-frontname=$MAGENTO_BACKEND_FRONTNAME --db-host=$MYSQL_HOST --db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER --db-password=$MYSQL_PASSWORD --use-secure=$MAGENTO_USE_SECURE --base-url-secure=$MAGENTO_BASE_URL_SECURE --use-secure-admin=$MAGENTO_USE_SECURE_ADMIN --admin-firstname=$MAGENTO_ADMIN_FIRSTNAME --admin-lastname=$MAGENTO_ADMIN_LASTNAME --admin-email=$MAGENTO_ADMIN_EMAIL --admin-user=$MAGENTO_ADMIN_USERNAME --admin-password=$MAGENTO_ADMIN_PASSWORD
composer require lomi/magento2-payments
/var/www/html/bin/magento module:enable Lomi_Payments --clear-static-content
/var/www/html/bin/magento setup:upgrade
/var/www/html/bin/magento setup:di:compile
EOSU

echo "Starting Apache..."
source /etc/apache2/envvars
exec apache2 -DFOREGROUND "$@"
